### ISSUE TITLE
Getting error "Illegal str: Length not a multiple of 2" in ethereumSignTx

### ISSUE THREAD

**Issue by amirsimhi** [trezor/connect#117]
Hey everyone,
I'm trying to sign ethereum transaction. I did everything like the example you mentioned in the documentaion: https://github.com/trezor/connect/blob/v4/examples/signtx-ethereum.html

but I'm getting this error "Illegal str: Length not a multiple of 2".
What does this error mean?

**Comment by szymonlesisz** [comment]
Hi @amirsimhi ,

Could you provide a input object that you are sending into TrezorConnect?
Basically this error means that some input field is not in hexadecimal format

**Comment by amirsimhi** [comment]
Thank you for your response @szymonlesisz. 
Here is an example input object that I used:

{"address":"m/44'/60'/0'/0",
"to":"c6725ae749677f21e4d8f85f41cfb6de49b9db29",
"data":"14c9035e0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000174876e80000000000000000000000000000000000000000000000000000000d1873d5639700000000000000000000000000000000000000000000000000000000005497c60000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001c2e9029557a8a62c02ee39b31304bb3626c53628f286a67af6d1cacebc7cf84d220e5c9ea82d43c26c9b0090917e48474913c4c25e43e4761319bf8877567f0ce0000000000000000000000000000000000000000000000000000000000000003000000000000000000000000c0829421c1d260bd3cb3e0f06cfe2d52db2ce3150000000000000000000000001f753d6fb3f13d869ff844b4ce37794d79a7ff1c0000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
"value":"174876e800",
"gasPrice":"12a9e8880",
"nonce":"01",
"gasLimit":"62ee2"}

**Comment by szymonlesisz** [comment]
"from":"0xbb58920ac8da844a39eb7cc747db25650d5625d2"
should be without "0x", it's not valid hex

try it with:
"from":"bb58920ac8da844a39eb7cc747db25650d5625d2"

**Comment by amirsimhi** [comment]
I fixed it to address":"m/44'/60'/0'/0" and it is still happening

**Comment by amirsimhi** [comment]
The from field hasn't been sent. Look at the object again I updated it

**Comment by szymonlesisz** [comment]
Sorry, i didn't notice that there is "address_n" field missing (instead of "from").
So your input should be like:

{"address_n":"m/44'/60'/0'/0",
"to":"c6725ae749677f21e4d8f85f41cfb6de49b9db29",
"data":"14c9035e0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000174876e80000000000000000000000000000000000000000000000000000000d1873d5639700000000000000000000000000000000000000000000000000000000005497c60000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001c2e9029557a8a62c02ee39b31304bb3626c53628f286a67af6d1cacebc7cf84d220e5c9ea82d43c26c9b0090917e48474913c4c25e43e4761319bf8877567f0ce0000000000000000000000000000000000000000000000000000000000000003000000000000000000000000c0829421c1d260bd3cb3e0f06cfe2d52db2ce3150000000000000000000000001f753d6fb3f13d869ff844b4ce37794d79a7ff1c0000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
"value":"174876e800",
"gasPrice":"12a9e8880",
"nonce":"01",
"gas":"62ee2"}

**Comment by amirsimhi** [comment]
Yes it is, but this is still happening :(

**Comment by szymonlesisz** [comment]
few more fixes after debugging.
You should look at example code more carefully:

Some expected fields that are missing in your code:
{
address_n: "value_in_bip44_format",
gas_price: "value_in_hex_format" (you have "gasPrice" instead, your value is not valid hex, it has 9 chars)
gas_limit: "value_in_hex_format" (you have "gas" instead, and also your value is not a valid hex, it has only 5 chars)
chain_id: number (missing field, 1 for ETH, 61 for ETC)
}
