### ISSUE TITLE
Open Questions for Trezor Connect and Trezor.js

### ISSUE THREAD

**Issue by jinchung** [trezor/connect#152]
Hello, I had some open questions after going through the documentation and some of the code.
Would be helpful if I could get in touch with someone to answer the following:

1. Is there any way I can easily get all the accounts on my Trezor using Trezor Connect without having a pop up per item? Do I need to preconstruct all the paths myself to request this information per currency or is there a way I can retrieve all of them (even non-BTC) without providing any path?

2. In one of your diagrams, it shows Trezor Connect uses trezor.js - does Trezor Connect use trezor.js? If Trezor Connect does not use trezor.js, where is the webusb logic in Trezor Connect?

3. To confirm, neither Trezor Connect nor trezor.js need to rely on the bridge or the Chrome extension to function in the Chrome web browser (they can use the WebUSB interface instead)

4. Does connecting to my Trezor require connecting to any Trezor servers? If so, what for?

**Comment by szymonlesisz** [comment]
Hi @jinchung ,

1. I'm not sure what you mean by "get all accounts". We don't have any method which returns full account information with transaction history included. We do have [TrezorConnect.getAccountInfo](https://github.com/trezor/connect/blob/develop/docs/methods/getAccountInfo.md) which return current balance, current address etc.

2. TrezorConnect v4 is using trezor.js module while TrezorConnect v5 has trezor.js logic builded inside. WebUSB logic could be found in [trezor-link](https://github.com/trezor/trezor-link/blob/master/src/lowlevel/webusb.js) module used in trezor.js [v4] or directly in TrezorConnect v5

3. TrezorConnect v4 is working with: Bridge1 (deprecated), Chrome Extension (deprecated), Bridge2 and WebUSB, TrezorConnect v5 works with Bridge2 and WebUSB only.

4. We are serving few elements from our domain (like popup) otherwise bridge, which has whitelisted origins set to "localhost" or "*.trezor.io" domains to avoiding CORS, will not work. We are also connecting our blockbook/bitcore servers to provide account transaction history. However if you decide to run your local backend and TrezorConnect instances there will be no connection to our servers at all.
