### ISSUE TITLE
Signed personal Ethereum messages starting with "0x" can not be verified

### ISSUE THREAD

**Issue by sterlu** [trezor/connect#155]
(Resubmiting the issue on this repo as discussed at https://github.com/trezor/trezor-mcu/issues/380)

Mainly, if a string starting with "0x" is signed, the signature can not be verified.

I've made a series of tests with different messages and am posting the results below. If a string is converted to a buffer prior to singing the signature is correct and verifiable. I am not sure if this is the expected behavior so I am resubmiting the issue. 

```
import ethUtil from 'ethereumjs-util';

// trezor login, etc.                      

await testMessageSigning('test');                            // OK
await testMessageSigning('12345');                           // OK
await testMessageSigning('0x12345');                         // FAIL
const dataBuff = ethUtil.toBuffer('0x12345');
await testMessageSigning(dataBuff)                           // OK
const msgHashBuff = ethUtil.hashPersonalMessage(dataBuff);
await testMessageSigning(msgHashBuff)                        // OK (ecrecover ok, but is signing a different message bascally so if you're not the one doing the verification this will not solve your problem)
await testMessageSigning(ethUtil.bufferToHex(msgHashBuff));  // FAIL (again failing with strings starting with '0x'
```

I have since deleted the script I used for results above but the `testMessageSigning` function was something along these lines: 
```
const testMessageSigning = (message) => {
  trezor.ethereumSignMessage("m/44'/60'/0'/0/0", message, (response) => {
    const signature = {
      r: `0x${response.signature.substr(0, 64)}`,
      s: `0x${response.signature.substr(64, 64)}`,
      v: parseInt(response.signature.substr(128), 16),
    }

    let pubKey = ethUtil.ecrecover(
      ethUtil.hashPersonalMessage(ethUtil.toBuffer(message)), 
      signature.v, 
      ethUtil.toBuffer(signature.r), 
      ethUtil.toBuffer(signature.s)
    );
    let retrievedAddress = ethUtil.bufferToHex(ethUtil.pubToAddress(pubKey));
    console.log(retrievedAddress === trezorAddress ? "OK" : "FAIL");
  })
}
```

**Comment by szymonlesisz** [comment]
Hi @sterlu,

I've just made some debug on this and you are right, Trezor will sign this message differently.
It's because "ethUtil" gets this value as a hexadecimal, convert it accordingly and add '0' at the beginning (left pad even)
Basically it means that ethUtil.toBuffer('0x12345') returns it as [1, 35, 69] > hex: '012345' while we are treating it as a string '0x12345' and our result is [48, 120, 49, 50, 51, 52, 53] > hex: '30783132333435'
If i use "ethUtil" way and check if incoming string is a hexadecimal it works fine, I was able to verify signed message on MEW while with out it i wasn't. The only problem is that message displayed on device will be **"#E"** instead of **"0x12345"** which could be confusing. @prusnak any throughts ?

**Comment by sterlu** [comment]
Hi @szymonlesisz,

I just wanted to clarify this behavior is present on Trezor Connect v4. I haven't been able to get it working at all on v5. (https://github.com/trezor/connect/blob/4ef73565866868cca5d3653d43d3d5e98e7246c7/src/js/core/methods/EthereumSignMessage.js#L42)

**Comment by szymonlesisz** [comment]
Yes, i put this TODO there because i wasn't sure if this is the way we want it to work. Like i said above, message on display will show value different from what user see in input (#E != 0x12345)
It doesn't matter v4 or v5, both treats incoming message as a string and hexlify it.
V5 isn't working for you?
Did you try it here?
https://trezor.github.io/connect-explorer/#/eth-signmessage

**Comment by szymonlesisz** [comment]
We discussed this issue and it looks like there is no ETH standard or EIP which says that we should detect if incoming message is a string or hexadecimal value and on top of that change this value by  splitting "0x" prefix and adding "0" for left pad even what totally modifies that message. Can you provide any link to prove that we should?

**Comment by prusnak** [comment]
Don't use `ethUtil.toBuffer` for passed message. The heuristics this function does is just crazy. 

From where I am standing everything works as expected if you avoid this function.

**Comment by szymonlesisz** [comment]
But if you still want to use ethUtil you should pass this message like this:
```
var messageFromEthUtil = ethUtil.toBuffer('0x12345');
TrezorConnect.ethereumSignMessage({
   path: "m/44'/60'/0'",
   message: messageFromEthUtil.toString()
});
```

Then it will be successfully verified by MEW which obviously is using ethUtil for decoding

**Comment by dekz** [comment]
Unless I am mistaken the problem with this is anything that cannot be encoded to utf8 will be broken. Ethereum uses hex as defacto so I'm not sure how/why ascii/utf8 became the default in Trezor. 

Trezor connect converts to [hex internally](https://github.com/trezor/connect/blob/aa9b98d73f9675713f76ed78f24e4b2468f0c0d2/src/js/core/methods/EthereumSignMessage.js#L42) anyway.

Is there any particular reason to not perform a NOOP when the string begins with '0x', or an additional optional parameter to modify the behaviour?

For example, hash some data on the client and request trezor to sign the hash, pretty common use case: `0x238ee635874c0b9a88435176680d1b42ca7559888dcea2655ff96ea17228fcb5` hopping into and out of utf8 encoding here will break as not all values can be encoded as utf8.
