### ISSUE TITLE
Trezor connect offline 

### ISSUE THREAD

**Issue by Ch1p999** [trezor/connect#160]
Is it possible to use trezor connect offline ?

I want to use this function in a web application 
https://github.com/trezor/trezor.js/blob/15c8f0a9c0386f360a30d2554cbc957e79ea45de/src/session.js#L322

is it available with trezor connect

**Comment by destrys** [comment]
I would also like offline functionality for Trezor Connect.

**Comment by szymonlesisz** [comment]
Hi,
Connect is designed to work inside of an invisible iframe hosted from trezor.io domain, which is trusted for users, and injected to a custom webpage or webextension. Otherwise Connect will not be able to communicate with trezor Bridge which expects http requests from certain origins (*.trezor.io or localhost)
However it's possible to run your own instance of Connect on localhost and then it could work without internet connection (with some restrictions of course, for example you wont be able to communicate with blockchain)

To run connect locally you need to clone current version of repository and run it:
yarn run dev / npm run dev

and then make sure that trezor-connect lib is pointing to a proper endpoint you need to set window variable:

window.__TREZOR_CONNECT_SRC = 'https://localhost:8088/';

**Comment by szymonlesisz** [comment]
@Ch1p999 

Yes, you can use this method. See docs:

https://github.com/trezor/connect/blob/develop/docs/methods/requestLogin.md
