### ISSUE TITLE
 Example of OP_RETURN output transaction fail

### ISSUE THREAD

**Issue by phoniex1** [trezor/connect#168]
I use example which demonstrates using Connect to send transaction with OP_RETURN output:
https://connect.trezor.io/4/examples/signtx-opreturn.html

but it 's fail, the error message is ( trezor one have initilized, and also has testnet BTC)
  "error": "txid 78dbd0d19ccf8776ac590225cde5797e439959d05b91ecdbacd7c244afb28542: -5: No such mempool or blockchain transaction. Use gettransaction for wallet transactions."
}

I think it's not use the right account which not pairing the txid, is it right?
or can you  tell me the right way to finish the transaction?
Thanks!

**Comment by prusnak** [comment]
Transaction `78dbd0d19ccf8776ac590225cde5797e439959d05b91ecdbacd7c244afb28542` does not exist, so this is wrong in the example

**Comment by phoniex1** [comment]
Thanks! what should i do to avoid the error? 
Or is there any other correct example for demonstrate  OP_RETURN with  Testnet for trezor ? 
@prusnak

**Comment by szymonlesisz** [comment]
It is Testnet valid transaction, however in this example TrezorConnect currency wasn't set to Testnet (so it was using Bitcoin by default).

You can also try it out with inputs/outputs used in this example with TrezorConnect version 5:
https://trezor.github.io/connect-explorer/#/sign-tx

Note: amount in output should be a string instead of number
