### ISSUE TITLE
Babel Polyfill 

### ISSUE THREAD

**Issue by jdetle** [trezor/connect#176]
I have a project that uses babel-polyfill itself, and babel throws an error when multiple polyfills are loaded ( for good reason ). Importing trezor-connect causes me to break the app, I'm going to introduce a PR to fix this by only requiring babel-polyfill if its not already loaded.

**Comment by szymonlesisz** [comment]
Hi @jdetle,
Thanks for PR. We decided to completely remove "babel-polyfill" from npm and inline script since many people are importing this by their own and it causes problems. 
However we've add another build with bundled "babel-polyfill".
Without polyfill:
https://connect.trezor.io/5/trezor-connect.js (or npm 5.0.29 package)

With polyfill:
https://connect.trezor.io/5/trezor-connect.min.js

**Comment by jdetle** [comment]
Thank you! Appreciate the quick turnaround! It looks like babel is removing babel-polyfill as well.
