### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by gislik** [trezor/connect#187]
When using the latest version 5.0.29 in a React app I'm getting a `ReferenceError: window is not defined`.

~~~~javascript
import TrezorConnect from 'trezor-connect';
~~~~

In the browser this is the stack trace.

~~~~
ReferenceError: window is not defined
    at Object.<anonymous> (/home/gislik/code/experiments/ledger-sign/node_modules/trezor-connect/lib/data/ConnectSettings.js:23:1)
    at Module._compile (module.js:652:30)
    at Module._compile (/home/gislik/code/experiments/ledger-sign/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/home/gislik/code/experiments/ledger-sign/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
~~~~

The bug seems to have been introduced between version 5.0.25 and 5.0.26. 

Best regards
Gisli

**Comment by szymonlesisz** [comment]
Hi @gislik,
Connect will not work for you without window reference since it uses multiple window methods like window.open or window.postMessage. I'm guessing that you are using server-side rendering in your app. Did it work before 5.0.25? 
Could you please make a little test for me and change few lines inside this package to make sure that this is the right solution? If this works i will change this line in npm package 

change:
./node_modules/trezor-connect/lib/data/ConnectSettings.js line 23

from
`var SRC = window.__TREZOR_CONNECT_SRC || '' + DEFAULT_DOMAIN + DIRECTORY;`
to
`var SRC = typeof window !== 'undefined' && window.__TREZOR_CONNECT_SRC ?  window.__TREZOR_CONNECT_SRC : '' + DEFAULT_DOMAIN + DIRECTORY;`

**Comment by gislik** [comment]
Hi @szymonlesisz 

Thank you for your quick reply. I agree this must be a consequence of server side rendering in my React setup. Yes, it did work with version 5.0.25.

I am however happy to report that the suggested changes do work. I no longer get the said error and I can communicate with the Trezor device. 

Thank you.

Best regards
Gísli

P.S. The "popup" now appears as a new tab but I guess that is intended and perhaps related to mobile wallet integrations.

**Comment by szymonlesisz** [comment]
Cool, i will put this update on the next release (5.0.30)
Yes, we decided to work with a new tab instead of a popup (for many reasons, mobiles are one of them)
