### ISSUE TITLE
Render iframe instead of popup/new tab

### ISSUE THREAD

**Issue by LukasRada** [trezor/connect#192]
[Question]
How to render Trezor unlock screen via PIN and stay on current page. Is there a way? Is it implemented in current version 5.x? Or is it future thing?

For better explanation see example of payment inline gateway:
https://help.gopay.com/en/knowledge-base/payment-gateway/procedure-of-payment-gateway/basic-features-of-the-inline-payment-gateway

**Comment by szymonlesisz** [comment]
You can't neither on v5 or any other and it's not a future thing. For security reasons it has to be served from our domain in our window.

**Comment by prusnak** [comment]
@LukasRada Let me expand a little. We don't want every website to communicate with Trezor, so we have to restrict this communication to our domain only. This removes the iframe option. I assume you were asking just because of the user experience as I can see no other reason to use iframe instead of a new tab. Please correct me if I am wrong and having an iframe instead of new tab is something more than just an user experience thing.

**Comment by LukasRada** [comment]
@prusnak Exactly as you wrote. I thought users would welcome to stay on current page and just enter PIN/Follow instructions on Trezor/etc.

But I understand now, security reasons are the highest priority. Got it.
Thank you.
