### ISSUE TITLE
Valid hex cannot be signed with ethereumSignMessage

### ISSUE THREAD

**Issue by cavanmflynn** [trezor/connect#216]
There is currently no way to sign hex messages that can't encode to utf-8 using `ethereumSignMessage`.

Trezor Connect will always [convert the passed message to hex](https://github.com/trezor/connect/blob/4ef73565866868cca5d3653d43d3d5e98e7246c7/src/js/core/methods/EthereumSignMessage.js#L43), regardless of if it's already hex. This means that we must encode the hex to utf-8 before passing it into `ethereumSignMessage` so Trezor Connect can convert it back as noted at the bottom of [this issue](https://github.com/trezor/connect/issues/155#issuecomment-412890358).

Unfortunately, any hex data that cannot be encoded as utf-8 is lost and replaced with the unicode replacement character (�).

For example:

```
const hexString = 'e86596f7e817cd263ba475d99463fe2bf4da00ce4825436070e2f7c987f4f52c';
const buffer = Buffer.from(hexString, 'hex');
buffer.toString('utf8') // �e����&;�uٔc�+���H%C`p��ɇ��,
Buffer.from(buffer.toString('utf8')).toString('hex') // efbfbd65efbfbdefbfbdefbfbd17efbfbd263befbfbd75d99463efbfbd2befbfbdefbfbd00efbfbd4825436070efbfbdefbfbdc987efbfbdefbfbd2c
```

To prevent data loss, `ethereumSignMessage` could check if the passed data is already hex and convert only if necessary. I have opened a PR to address this issue: https://github.com/trezor/connect/pull/215

**Comment by szymonlesisz** [comment]
merged in https://github.com/trezor/connect/pull/219
thanks!

**Comment by szymonlesisz** [comment]
since this feature could break existing implementation (see here: https://github.com/trezor/connect/issues/222) We decided to add a new parameter to this method.
If you want to sign a hexed string you need to add "hex" parameter set to "true"
more in [docs](https://github.com/trezor/connect/blob/develop/docs/methods/ethereumSignMessage.md)

**Comment by destrys** [comment]
@cavanmflynn I feel your pain on this. I think the underlying problem is that the Trezor Device itself accepts the message in hex, but then displays it on the device in ascii. So even if you pass it hex data, it won't display on the device correctly, and then how can you trust that you are signing the message you intended to sign?

We took that into account when writing our eth contract, converting the expected message into the ascii encoding of the hex data ( see https://github.com/unchained-capital/ethereum-multisig/blob/master/contracts/MultiSig2of3.sol#L207-L226).

Looking at the trezor firmware, it looks like they may be adding the ability to display hex data without converting to ascii first:
https://github.com/trezor/trezor-mcu/blob/master/firmware/layout2.c#L384-L388
