### ISSUE TITLE
Public api to list connected & paired devices

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/connect#368]
What's the preferred way in `TrezorConnect.init({ popup: false })`-style clients to enumerate connected devices, and request pairing (in the case of WebUsb devices)?

**Comment by szymonlesisz** [comment]
It depends on what kind of application you have in mind. 
`popup: false` can be used only for connect hosted locally, it will not work from regular website implementation due to security reasons (iframe will not accept this value and will set it to `true`)
Currently due to changes in chrome 72 webusb in `popup` mode is disabled, we need to redesign pairing with webusb device WITIN 3rd party website instead of popup.

However if you trying to run it from localhost/electron (electron doesn't work with webusb) there is no preferred way, its up to you want you want to do after you application start. For example our wallet use it like this:

1. Wallet received TRANSPORT_EVENT which tells what kind of transport is available (brigde - primary, webusb - secondary)
2. If transport is `webusb` type and there is no at least one device connected (DEVICE_EVENT wasn't emitted) wallet renders "check for devices" button using `TrezorConnect.renderWebUSBButton('.element-class-name')`
3. After pairing action `DEVICE_EVENT:connected` should be emitted

**Comment by keepkeyjon** [comment]
Oh, damn. That kills the use case I had in mind. What's the security consideration here?

I'll assume `popup: true` for now, and we can talk about whether you're willing to whitelist our URL later.

**Comment by szymonlesisz** [comment]
The main security reason for this is that you don't want to some random 3rd party website enumerate your device without your knowledge/permission. You may become an easy target for phishing since they already know that you have Trezor
