### ISSUE TITLE
Issue with Litecoin bech32 m/84/2/0 Path.

### ISSUE THREAD

**Issue by eabz** [trezor/connect#381]
Hello again,
I am trying to get a Litecoin bech32 extendedPubKey from Trezor wallet using this function:
```
TrezorConnect.getPublicKey({ path: "m/84'/2'/0'", coin: "ltc" });
```

I am getting this response:
```
{
	"id": 1,
	"payload": {
		"code": "Failure_DataError",
		"error": "Invalid combination of coin and script_type"
	},
	"success": false
}
```

**Comment by tsusanka** [comment]
This is fixed in [trezor-core](https://github.com/trezor/trezor-core) master branch and will be shipped in the next release.

For reference: in 2.1.0 some segwit coins did not have the `xpub_magic_segwit_native` field properly set. This was fixed in https://github.com/trezor/trezor-common/commit/792a4eddb5afa366181b7b2f8a5d84532b31a6a1
