### ISSUE TITLE
Komodo coin support and outdated lib bitcoinjs-lib-zcash

### ISSUE THREAD

**Issue by smdmitry** [trezor/connect#396]
I want to integrate Komodo coin support to Connect, but Trezor Connect uses deprecated library bitcoinjs-lib-zcash here https://github.com/trezor/connect/blob/develop/src/js/backend/BlockBook.js#L8

How can this be resolved? Please look at my PR: https://github.com/karel-3d/bitcoinjs-lib/pull/13

Maybe its better use newer version of this lib supported by Trezor: https://github.com/trezor/trezor-utxo-lib/?

**Comment by szymonlesisz** [comment]
Hi @smdmitry 
I've already added Komodo to https://github.com/trezor/trezor-utxo-lib/tree/trezor/src, rewrote connect to implement this new library in branch [v8-beta](https://github.com/trezor/connect/tree/v8-beta) (this one replaces bitcoinjs-lib) BUT during tests and implementation we decided that we need to 
split `connect` repository to monorepo structure to properly add nodejs, react-native and electron support.

That's why i need to to ask you to be patient.
New version of connect should be done by the end of the moth,

I will let you know here,

**Comment by keraf** [comment]
Komodo support has been added. Closing issue for now. Feel free to open new issues if you encounter issues using this coin with trezor-connect.
