### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by runn1ng** [trezor/connect#41]
We should add some license probably

We have GPLv3 in popup/package.json, but it's not clear how relevant it is

**Comment by slush0** [comment]
It can be GPLv3.

**Comment by prusnak** [comment]
Set to  LGPL-3.0 in https://github.com/trezor/connect/commit/6165a94bff8ad83bced00e4e7d84cbc8f7840abf like the rest of TREZOR stuff.

**Comment by splix** [comment]
Is it possible to release it under dual license? LGPL + MIT/BSD/APACHE? that will allow to use it from non-GPL applications too

**Comment by prusnak** [comment]
You don't embed Connect directly into another applications. You communicate with Connect via API, which is allowed in LGPL. No need to change license for non-GPL apps.

**Comment by splix** [comment]
We're working on desktop app, so it means we'll need to include that lib into the app distribution

**Comment by prusnak** [comment]
I think you want to use https://github.com/trezor/trezor-link then rather than Connect. But that is irrelevant anyway, because:

You can still use LGPL library in non-LGPL code. (Notice the "L", it's LGPL not GPL). If you don't change the library code you don't need to do anything. If you change the library you need to contribute changes back.

**Comment by splix** [comment]
Ah, I see, thank you for the link. Unfortunately LGPL too, but I got it, thank you

Usually we have a big JS compiled from sources and all libraries. We can't put LGPL library code into that compiled JS, because it requires for lib to be used as a shared lib (separable/replaceable/etc). See https://www.gnu.org/licenses/lgpl-3.0.en.html ("p4. Combined Works" especially). 

We can use it as a shared lib, of course, but it's not really convenient. So I'm asking, if it's possible to relicense, that will make it easier to use.

PS we distribute the app as Open Source too, but under Apache2 licence. LGPL requires xGPL if embedded.

**Comment by prusnak** [comment]
I think you are not violating LGPL when you distribute compiled JS. See https://opensource.stackexchange.com/questions/5139/does-compiling-a-js-bundle-with-webpack-browserify-violate-the-lgpl-license

Out of curiosity: what is the app you are making?

**Comment by splix** [comment]
Yeah, I know there are opposite views on this, but it's a grey area. I don't want to risk going to court, even if know that `Zimm i48` will come and explains to the prosecutor that they simply misunderstood LGPL license.

As I mentioned, we can use it as a separate shared lib. Just wanted to ask if you want to keep it under LGPL only or maybe you plan to add additional license.

It's Ethereum Classic wallet https://github.com/ethereumproject/emerald-wallet

**Comment by prusnak** [comment]
I prefer to keep this under LGPL-3.0+ for the time being.
