### ISSUE TITLE
EOS eosGetPublicKey error: "Iframe timeout"

### ISSUE THREAD

**Issue by jafri** [trezor/connect#424]
@szymonlesisz  Getting the following error after new window is opened:

```
{error: "Iframe timeout"}
```

on first login with ```TrezorConnect.eosGetPublicKey```

**Comment by jafri** [comment]
The second time the function is called, it goes a little further:

<img width="440" alt="Screen Shot 2019-07-23 at 3 36 30 PM" src="https://user-images.githubusercontent.com/13677357/61749533-363ddb80-ad60-11e9-8bdd-d0320f5a3c52.png">
<img width="477" alt="Screen Shot 2019-07-23 at 3 36 39 PM" src="https://user-images.githubusercontent.com/13677357/61749543-3b9b2600-ad60-11e9-9e6b-ede9171ea4ed.png">
<img width="363" alt="Screen Shot 2019-07-23 at 3 36 53 PM" src="https://user-images.githubusercontent.com/13677357/61749551-3fc74380-ad60-11e9-8f2b-f2410c53c58f.png">

After pressing accept, this is all it shows:

<img width="467" alt="Screen Shot 2019-07-23 at 3 41 23 PM" src="https://user-images.githubusercontent.com/13677357/61749681-8a48c000-ad60-11e9-886d-f0139eef6679.png">

There is no result or error returned to my app either, only this warning from when the new tab was opened:
```
iframe postMessage: popupMessagePort not found
```

**Comment by jafri** [comment]
Here is a testing URL, press login in top right and Trezor: https://5d37871e5ca929000ab4aaad--determined-carson-b95cce.netlify.com/

**Comment by szymonlesisz** [comment]
maybe it will be easier to debug if you provide some code.
Here's mine working example:
https://jsfiddle.net/szlesisz/53uk06yL/

**Comment by jafri** [comment]
@szymonlesisz thank you for the example.

It looks like all the issues were coming from setting appUrl to 'https://bloks.io' instead of 'bloks.io'

**Comment by szymonlesisz** [comment]
so it will be a connect issue in manifest function, thanks for pointing that i will fix it in next release

**Comment by szymonlesisz** [comment]
try with 7.0.5, it should be working with 'https://bloks.io' as well

**Comment by jafri** [comment]
Works great 🥇 🥇 🥇 

Try it out at https://bloks.io

**Comment by mattwinans** [comment]
Can we reopen this? I'm suddenly getting the same error nearly 4 years later and this is the ONLY Google Result that discusses it.

I had this issue a while back and haven't had it in many months... but it appears to be back again.

48 second demonstration of the issue:
https://youtu.be/hEPm8GNOaas

When I attempt to swap in Pancake Swap via Metamask, the window that pops up to initiate my Trezor device and asks for my PIN...

https://connect.trezor.io/8/popup.html#loading

...never finishes loading and closes about 3 seconds in.

This is a gigantic issue for me because right now I cannot even access my funds with this issue. I cannot buy or sell and it is VERY concerning!
