### ISSUE TITLE
[QUESTION] Why `signTransaction` has such cumbersome interface?

### ISSUE THREAD

**Issue by maxd** [trezor/connect#472]
Trezor Wallet has [simple UI](https://wiki.trezor.io/User_manual-Making_payments#Enter_the_destination_address_and_the_amount) to transfer money (need to fill ~3 fields: `Destination Address`, `Amount`, `Currency`). Some Trezor Connect methods has similar interface (i.e. `ethereumSignTransaction` or `rippleSignTransaction` methods). 

But `signTransaction` has completely different interface. For example if I want to make Bitcoin transfer I should fill bunch of inputs and outputs instead of specifing `Destination Address`, `Amount`, `Currency`. 

Could you please explain why `signTransaction` has such cumbersome interface and why Trezor Connect doesn't have `bitcoinSignTransaction` method with simplified interface?

**Comment by szymonlesisz** [comment]
It's caused by complexity of Bitcoin (and other bitcoin-like coins).
You need to known your inputs and their previous transactions in order to sign them.
The wallet UI that you are referring to is simplified because wallet already knows those data from account discovery process but i can ensure you that they are used during in signTransaction.
