### ISSUE TITLE
composeTransaction function does nothing.

### ISSUE THREAD

**Issue by dixefaj949** [trezor/connect#565]
I am trying to use the composeTransaction function to send bitcoin, It does not return a error, no success message and there is nothing displayed on my trezor.
This is my code:
`var TrezorConnect = require('trezor-connect').default;
//var TrezorConnect = require('./tools');

TrezorConnect.manifest({
    email: 'developer@xyz.com',
    appUrl: 'http://your.application.com'
})

// params are key-value pairs inside Object
TrezorConnect.composeTransaction({
    outputs: [
        { amount: "200000", address: "ADDRESSHERE" }
    ],
    coin: "btc",
    push: true
});`

I am not sure whats going on, any help is appreciated.

**Comment by dixefaj949** [comment]
`var TrezorConnect = require('trezor-connect').default;
//var TrezorConnect = require('./tools');

TrezorConnect.manifest({
    email: 'developer@xyz.com',
    appUrl: 'http://your.application.com'
})


// params are key-value pairs inside Object
TrezorConnect.composeTransaction({
    outputs: [
        { amount: "200000", address: "ADDRESSHERE" }
    ],
    coin: "btc",
    push: true
});`

**Comment by szymonlesisz** [comment]
it should be working like this:
https://trezor.github.io/connect-explorer/#/method/composeTransaction

Whats your setup? (connect version, browser, etc)

**Comment by dixefaj949** [comment]
Connect version is latest, unsure what you mean by browser though. I know that my device is being connected to the nodejs app because the screen flashes on when i run it.

**Comment by szymonlesisz** [comment]
that is exactly what i mean. trezor-connect acts differently in browser and node.
since you are using node you need to listen UI events for your self and respond to them.
`TrezorConnect.on(UI_EVENT, (ev) => console.log(ev))` will be helpful

This method has two modes:

**Discovery mode** (see the example in connect-explorer above)
- provides a full discovery of all accounts, 
- let you pick from one of them using UI.SELECT_ACCOUNT and expecting `TrezorConnect.uiResponse`
- asks for fee, again expects `TrezorConnect.uiResponse`
....
this one is not suitable for nodejs since you need to handle all UI.REQUESTS and RESPONSE for yourself (however you can still do it if you want to)

**Account mode (precompose)**
- without discovery, with `Account` object as a param. You can get Account object using `TrezorConnect.getAccountInfo`
- receive precomposed and calculated transaction ready (on not) to sign

It's not very intuitive and not documented at all, thats why i've decided to do this example for you:

https://gist.github.com/szymonlesisz/84050969133e3de99d6768f27046e38d

**Comment by dixefaj949** [comment]
> that is exactly what i mean. trezor-connect acts differently in browser and node.
> since you are using node you need to listen UI events for your self and respond to them.
> `TrezorConnect.on(UI_EVENT, (ev) => console.log(ev))` will be helpful
> 
> This method has two modes:
> 
> **Discovery mode** (see the example in connect-explorer above)
> 
> * provides a full discovery of all accounts,
> * let you pick from one of them using UI.SELECT_ACCOUNT and expecting `TrezorConnect.uiResponse`
> * asks for fee, again expects `TrezorConnect.uiResponse`
>   ....
>   this one is not suitable for nodejs since you need to handle all UI.REQUESTS and RESPONSE for yourself (however you can still do it if you want to)
> 
> **Account mode (precompose)**
> 
> * without discovery, with `Account` object as a param. You can get Account object using `TrezorConnect.getAccountInfo`
> * receive precomposed and calculated transaction ready (on not) to sign
> 
> It's not very intuitive and not documented at all, thats why i've decided to do this example for you:
> 
> https://gist.github.com/szymonlesisz/84050969133e3de99d6768f27046e38d

nice, whats your bitcoin address?

**Comment by szymonlesisz** [comment]
`35J6G3ZXr65ySx942fpGUsyRgXaFsAvrb7` :)

**Comment by dixefaj949** [comment]
> 35J6G3ZXr65ySx942fpGUsyRgXaFsAvrb7

I am trying to send $20 to your address with the sample code you sent me, I get this error now:
> Error: This version of trezor-connect is not suitable to work without browser
I have looked it up and i cant see a clear fix, My trezor bridge version is: 2.0.27

**Comment by szymonlesisz** [comment]
ah, yes, you ned to install `8.1.1-extended`
trezor-connect was created as browser only lib and have minimum dependencies, node support comes later therefore it needs different (extended) dependencies
