### ISSUE TITLE
Generated address not receiving funds.

### ISSUE THREAD

**Issue by dixefaj949** [trezor/connect#567]
Hello,

I have a loop that generates 100 bitcoin mainnet addresses using the TrezorConnect.getAddress function. My trezor receives the funds if i send to the first address generated, and the lower numbers (addresses 1 - 20 work). However, If i try and send to the 99th address generated for example, I wont receive the funds in my trezor wallet.

**Comment by szymonlesisz** [comment]
Looking up at your account balance (discovery process) has to be limited otherwise it will took forever to check EVERY possible address on your account.
Basically this process is designed to take 20 addresses and if there is something on them, takes another batch of 20 and loops until every address batch is not used.
Trezor wallet will not allow you to generate more than 20 empty addresses, therefore we ensure that the situation described above will never happen.

However you can increase this gap using custom param:
```javascript
TrezorConnect.getAccountInfo({
        path: "m/49'/1'/0'",
        coin: "test,
        details: 'tokenBalances',
         gap: 100
});
```

**Comment by dixefaj949** [comment]
> Looking up at your account balance (discovery process) has to be limited otherwise it will took forever to check EVERY possible address on your account.
> Basically this process is designed to take 20 addresses and if there is something on them, takes another batch of 20 and loops until every address batch is not used.
> Trezor wallet will not allow you to generate more than 20 empty addresses, therefore we ensure that the situation described above will never happen.
> 
> However you can increase this gap using custom param:
> 
> ```js
> TrezorConnect.getAccountInfo({
>         path: "m/49'/1'/0'",
>         coin: "test,
>         details: 'tokenBalances',
>          gap: 100
> });
> ```

I run that code and it generates the addresses, I send bitcoin to one of them and its not received in my wallet.

**Comment by szymonlesisz** [comment]
like i said, if we are talking about trezor wallet it looks up using 20 items in batch, since your gap is greater it will no look further. Suggested solution:

Spend this input using TrezorConnect (with the script i've send you) and never do this kind of gaps if you want to see your balance in trezor wallet
