### ISSUE TITLE
Cannot call some methods if not backed up.

### ISSUE THREAD

**Issue by JoeGruffins** [trezor/connect#667]
Running with popup=false and using the emulator. If the wallet is not backed up this method hangs indefinitely.

https://github.com/trezor/connect/blob/966063c5e4eaa000a7a03024268bfac062c2ecc0/src/js/core/methods/GetAddress.js#L148-L157

**Comment by szymonlesisz** [comment]
Hi @JoeGruffins 
since you are not using popup you need to handle all the requests/events by yourself

in this case you need to set listener to a UI_EVENT and send the decision back to connect:

```
import TrezorConnect, { UI_EVENT, UI } from 'trezor-connect';

TrezorConnect.on(UI_EVENT, event => {
    if (event.type === UI.REQUEST_CONFIRMATION) {
        // display some warning
        // and send user decision:
        TrezorConnect.uiResponse({
            type: UI.RECEIVE_CONFIRMATION,
            payload: decision, // (decision: boolean)
        });
    }
});
```

It's important to warn the user about potential coin loss. if you send something into not backed up device and then you lost the device then there is a high chance that you don't have backup for your seed and your coins will be gone forever

see:
https://github.com/trezor/connect/blob/develop/src/html/popup.html#L1515-L1527

**Comment by keraf** [comment]
Hi @JoeGruffins, do you need further help with this issue or is it good to close?

**Comment by JoeGruffins** [comment]
Thanks!
