### ISSUE TITLE
Passphrase problems

### ISSUE THREAD

**Issue by tylerdmace** [trezor/connect#817]
Hello gang. I've got a little research project I'm playing with and I need help understanding the correct way to handle some passphrase requests that seem to be happening before I can subscribe to UI events. I have a webusb / no-popup app I'm working on where I do the following (in order):
```javascript
resetDevice({passphrase_protection: true, useEmptyPassphrase: false});
```
then:
```javascript
applySettings({label: 'Test Device'});
```
then:
```javascript
changePin({remove: false});
```
I have some subscriptions to the UI events that respond automatically for me:
```javascript
TrezorConnect.on(UI_EVENT, event => {
  if(event.type === UI.REQUEST_PASSPHRASE) {
    this.uiResponse({type: UI.RECEIVE_PASSPHRASE, payload: {value: 'test passphrase', save: true, passphraseOnDevice: false}});
  }

  this.publish(UI_EVENT, event);
});
```
My problem is that when I run `applySettings()` after having successfully `resetDevice()`, I see `trezor-link` activity where a passphrase request occurs and a response automatically happens but with an empty string as the payload: `{passphrase: ""}`. I believe this is causing later API calls (for example, calling `ethereumGetAddress()`) to fail with: `Passphrase is incorrect.`. Can anyone shed any light on this? What am I doing wrong?

**Comment by szymonlesisz** [comment]
Hi @tylerdmace ,
This is quite odd because passphrase request should not be triggered until you start working with private keys. 
None of management method (wipeDevice, resetDevice, applySettings, changePin etc) should require that and i've just verify that by doing the same thing as you described.

Could you provide some logs? You can enable it in `TrezorConnect.init({ ...., debug: true }`
