### ISSUE TITLE
Failed Transaction: Error: Device Call In Progress

### ISSUE THREAD

**Issue by JoseIrving** [trezor/connect#962]
I have a problem with my metamask that I didn't have before, it is connected to a trezor hardware wallet and I get an error when I want to sign the transaction "Error: Device Call in Progress" and the Trezor pop up remains in Loading, can anyone help me. I use google chrome, Dell windows 11.
![image](https://user-images.githubusercontent.com/95604194/144791023-f1676380-1912-4615-8b92-bcfcb470cba1.png)

**Comment by mroz22** [comment]
Hello,  do you have the latest firmware? you can check in https://suite.trezor.io/web/ 

Otherwise I am not aware of any changes made recently that could affect you. So maybe please restart everything and try again. If it does not help I will ask trezor QA team to try to replicate your issue. In that case, providing as much information on what you are trying to do and what system you use will be hepful.

**Comment by mroz22** [comment]
If you manage to gather more info, please reopen this issue.
