### ISSUE TITLE
EthereumGetAddress checksum 

### ISSUE THREAD

**Issue by mroz22** [trezor/connect#987]
https://github.com/trezor/connect/blob/e1c78c23feaf864b228fd2ed53daec947548d777/src/js/device/DeviceCommands.js#L293

this should (could) run only for specific firmwares and if those are not supported anymore, we can probably remove this. Is that right? @matejcik ?

**Comment by matejcik** [comment]
Both T1 and TT firmwares always return checksummed address. This change has been implemented ever since this commit sequence:
https://github.com/trezor/trezor-firmware/commit/6a39049cc157faa8fc5a5922d308bf6c3cccda1f
https://github.com/trezor/trezor-firmware/commit/534d15f208dccb1091f85381c9946d7c97c7c881
https://github.com/trezor/trezor-firmware/commit/101242f902bc628a076dca6e91a89ba3e390e116

These are in use since T1 1.8.1 and TT 2.1.1.

If Connect doesn't currently support the old `bytes` fields, it also means that the `toChecksumAddress` calls can be omitted.

**Comment by mroz22** [comment]
Thanks! 
right now minimum supported versions for ethereum are 
-  t1 1.8.0
 - tt 2.1.0

 so I guess we should bump this by one patch version t obe able to ditch `toChecksumAddress`

**Comment by matejcik** [comment]
no wait, this is just what trezor-firmware repo is showing me. the change is actually older, let me check.

**Comment by mroz22** [comment]
ok, nevermind, if its older, we are good. I don't need exact numbers here. thanks!

**Comment by matejcik** [comment]
confirming that versions 2.1.0 and 1.8.0 seem to be what introduced this change. so you should be safe to drop the `toChecksumAddress` calls

**Comment by mroz22** [comment]
thanks, it is already in develop :partying_face: so I am closing this issue.
